# Change these first time
owner: vietnv1995 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: API EZMatch Check HasFace
    url: https://faceapi.mobidev.asia
    method: GET
    maxResponseTime: 2000 # ms
    expectedStatus: 200

  - name: API Easy3P Main
    url: https://api.easy3p.com
    method: GET
    maxResponseTime: 2000 # ms
    expectedStatus: 200
    
  - name: Test Brocken
    url: https://api.easy3p.com
    method: GET
    maxResponseTime: 2000 # ms
    expectedStatus: 200

# Cấu hình status website với baseUrl
status-website:
  # QUAN TRỌNG: Thêm baseUrl để fix lỗi đường dẫn
  baseUrl: /upptime
  
  name: Status Monitor
  introTitle: "Trang theo dõi trạng thái hệ thống"
  introMessage: "Theo dõi real-time trạng thái hoạt động của các dịch vụ"
  
  navbar:
    - title: Trang chủ
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

notifications:
  - type: slack
    webhook-url: $SLACK_WEBHOOK_URL

# Assignees
# assignees:
#   - vietnv1995

# Cấu hình commit messages  
# commitMessages:
#   readmeContent: ":pencil: Cập nhật tóm tắt trong README [skip ci] [upptime]"
#   summaryJson: ":card_file_box: Cập nhật tệp tóm tắt trạng thái [skip ci] [upptime]"
#   statusChange: "$EMOJI $SITE_NAME là $STATUS ($RESPONSE_CODE trong $RESPONSE_TIME ms) [skip ci] [upptime]"
#   graphsUpdate: ":bento: Cập nhật biểu đồ [skip ci] [upptime]"

# Cấu hình schedule
workflowSchedule:
  graphs: "0 0 * * *"        # 5 trường: phút giờ ngày tháng thứ
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"      # Và thêm uptime schedule

# status-website:
#   # Add your custom domain name, or remove the `cname` line if you don't have a domain
#   # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
#   cname: demo.upptime.js.org
#   # baseUrl: /your-repo-name
#   logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
#   name: Upptime
#   introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
#   introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
#   navbar:
#     - title: Status
#       href: /
#     - title: GitHub
#       href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
